using BACKEND_CQRS.Application.Dto;
using BACKEND_CQRS.Application.Wrapper;
using MediatR;
using System;

namespace BACKEND_CQRS.Application.Command
{
    public class CreateSprintCommand : IRequest<ApiResponse<CreateSprintDto>>
    {
        // Id is auto-generated by the server - do not include in request
        public Guid? ProjectId { get; set; } // Optional
        public string SprintName { get; set; } = string.Empty; // Required
        public string? SprintGoal { get; set; } // Optional
        public int? TeamAssigned { get; set; } // Optional
        public DateTime? StartDate { get; set; } // Optional
        public DateTime? DueDate { get; set; } // Optional
        public string? Status { get; set; } = "PLANNED"; // Optional, defaults to PLANNED
        public decimal? StoryPoint { get; set; } // Optional
    }
}
